config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :advertisements
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'search#index'

  get '/' => 'search#index'
  get '/result' => 'search#result'

  get '/signup', to: 'users#new' # match '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get '/advertisement/free', to: 'advertisements#free'
  get '/advertisement/add_free_book', to: 'advertisements#add_free_book'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user

  default_scope { order('advertisements.created_at DESC') } #DESC = descending

  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :price, presence: true
  validates :preferred_contact, presence: true
  validates :location, presence: true
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_filter :signed_in_user, only: [:new, :create, :show, :destroy]
  before_filter :correct_user, only: [:show, :destroy]

  def index
  end

  def free
  end

  def add_free_book
    if params[:title] == "" || params[:author] == "" || params[:subject] == "" || params[:pdfLink] == ""
      flash[:danger] = "One or more field missing"
      redirect_to '/advertisement/free'
    else
      response = post_solr_request(params[:title], params[:author], params[:subject], params[:pdfLink].split(/\r?\n/))
      puts response
      flash[:success] = "Your newly added book is now searchable!"
      redirect_to current_user
    end
  end

  def new
    @advertisement = Advertisement.new
  end

  def create
    @advertisement = current_user.advertisements.build(advertisements_params)
    if @advertisement.save
      flash[:success] = "Advert successfully created!"
      redirect_to @advertisement
    else
      flash[:danger] = "Avert could not be created. Try again!"
      render 'new'
    end
  end

  def show
    @advertisement = current_user.advertisements.find(params[:id])
  end

  def edit
    @advertisement = current_user.advertisements.find(params[:id])
  end

  def update
    @advertisement = current_user.advertisements.find_by_id(params[:id])
    if @advertisement.update_attributes(advertisements_params)
      flash[:success] = "Advertisement Updated"
      redirect_to @advertisement
    else
      render 'edit'
    end
  end

  def destroy
    @advertisement.destroy
    return_back_or root_path
  end

  private
    def advertisements_params
      params.require(:advertisement).permit(:title, :price, :content, :preferred_contact, :location)
    end

    def correct_user
      @advertisement = current_user.advertisements.find_by_id(params[:id])
      redirect_to root_path if @advertisement.nil?
    end

    def post_solr_request(title, author, subject, links)
      uri = URI.parse("http://ec2-52-40-24-42.us-west-2.compute.amazonaws.com:8983/solr/TEXTBOOK_DB/update/json/docs?commit=true")
      data = "{
          \"title\":\"#{title}\",
          \"author\":\"#{author}\",
          \"subject\":\"#{subject}\",
          \"user\":\"#{current_user.email}\",
          \"password\":\"filtered\",
          \"pdfLink\": #{links}
        }"
      req = Net::HTTP::Post.new(uri, {'Content-Type' => 'application/json'})
      req.body = data

      http = Net::HTTP.new(uri.host, uri.port)
      response = http.request(req)
      response
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper

  def free_advertisement_path
    "/advertisement/free"
  end

end

app/views/advertisements/_advertisement.html.erb
<li>
  <span class="content">
    <%= link_to advertisement.title, advertisement_path(advertisement.id) %>
  </span>

  <span class="timestamp">
    Posted <%=time_ago_in_words(advertisement.created_at)%> ago
  </span>
</li>

app/views/advertisements/edit.html.erb
<h1>Edit Advertisement</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@advertisement) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p><%= f.label :title %></p>
      <%= f.text_field :title, placeholder: "e.g. Grounding for the Metaphysics of Morals by Kant" %>
      <br>
      <p><%= f.label :price %></p>
      <%= f.text_field :price, placeholder: "e.g. 12.99"%>
      <br>
      <p><%= f.label :content %></p>
      <%= f.text_area :content, placeholder: "e.g. This books is brand new, please contact me via phone 661-XXX or email@email.com" %>
      <br>
      <p><%= f.label :preferred_contact %></p>
      <%= f.text_field :preferred_contact, placeholder: "email@email.com" %>
      <br>
      <p><%= f.label :location %></p>
      <%= f.text_field :location, placeholder: "UCI, Irvine, CA"%>
      <br>
      <%= f.submit "Post Ad!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/advertisements/free.html.erb
<div class="row">
  <div class="span6 offset3">
    <h1>Share an online link your found for free!</h1>
    <form class="" action="add_free_book" method="get" id="freebookform">
      <p>Title:</p>
      <input type="text" name="title">
      <br>
      <p>Author:</p>
      <input type="text" name="author">
      <br>
      <p>subject:</p>
      <input type="text" name="subject">
      <br>
      <p>pdf links:</p>
      <textarea rows="4" cols="50" name="pdfLink" form="freebookform" placeholder="Insert one link per line"></textarea>
      <br><br>
      <input type="submit" value="Submit">
    </form>
  </div>
</div>

app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@advertisement) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <p><%= f.label :title %></p>
      <%= f.text_field :title, placeholder: "e.g. Grounding for the Metaphysics of Morals by Kant" %>
      <br>
      <p><%= f.label :price %></p>
      <%= f.text_field :price, placeholder: "e.g. 12.99"%>
      <br>
      <p><%= f.label :content %></p>
      <%= f.text_area :content, placeholder: "e.g. This books is brand new, please contact me via phone 661-XXX or email@email.com" %>
      <br>
      <p><%= f.label :preferred_contact %></p>
      <%= f.text_field :preferred_contact, placeholder: "email@email.com" %>
      <br>
      <p><%= f.label :location %></p>
      <%= f.text_field :location, placeholder: "UCI, Irvine, CA"%>
      <br>
      <%= f.submit "Post Ad!", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/advertisements/show.html.erb
<div class="row">
  <div class="offset3 span6">
    <h1><%= @advertisement.title %></h1>
    <hr>
    <h3>$ <%= @advertisement.price %></h3>
    <p><%= @advertisement.content %></p>

    <br>
    <p><b>preferred contact:</b> <%= @advertisement.preferred_contact%></p>
    <p><b>location:</b> <%= @advertisement.location %></p>
    <p>Posted <%= @advertisement.created_at.to_date %> (<%= time_ago_in_words(@advertisement.created_at)%> ago)</p>
  </div>

  <% if current_user?(@advertisement.user) %>
    <%= link_to "edit ad", edit_advertisement_path(@advertisement.id), class: "btn btn-large btn-primary" %>
    <%= link_to "delete ad", @advertisement, method: :delete, data: { confirm: "are you sure?", title: @advertisement.title }, class: "btn btn-large btn-primary" %>
  <% end %>
</div>